// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	APIApps    string
	AppTokens  string
	UserTokens string
	Users      string
}{
	APIApps:    "api_apps",
	AppTokens:  "app_tokens",
	UserTokens: "user_tokens",
	Users:      "users",
}
